// Comprehensive list of cool session names for SmarpStream
// Organized by categories for easy reference and expansion

module.exports = {
  // Power & Energy Adjectives
  adjectives: [
    'Swift', 'Bright', 'Sharp', 'Bold', 'Quick', 'Smart', 'Fast', 'Cool',
    'Fresh', 'Prime', 'Elite', 'Noble', 'Royal', 'Grand', 'Super', 'Ultra',
    'Mega', 'Turbo', 'Flash', 'Blaze', 'Storm', 'Thunder', 'Lightning', 'Rocket',
    'Apex', 'Peak', 'Summit', 'Zenith', 'Crown', 'Star', 'Nova', 'Cosmic',
    'Epic', 'Legend', 'Mythic', 'Divine', 'Sacred', 'Ancient', 'Eternal', 'Infinite',
    'Neon', 'Plasma', 'Fusion', 'Atomic', 'Nuclear', 'Electric', 'Magnetic', 'Dynamic',
    'Vibrant', 'Radiant', 'Luminous', 'Brilliant', 'Dazzling', 'Glowing', 'Shimmering', 'Sparkling',
    'Powerful', 'Mighty', 'Strong', 'Fierce', 'Intense', 'Vivid', 'Bold', 'Brave',
    'Crystal', 'Diamond', 'Platinum', 'Gold', 'Silver', 'Chrome', 'Steel', 'Titanium',
    'Quantum', 'Neural', 'Digital', 'Cyber', 'Virtual', 'Hyper', 'Meta', 'Nano',
    'Alpha', 'Beta', 'Gamma', 'Delta', 'Omega', 'Sigma', 'Lambda', 'Theta',
    'Velocity', 'Momentum', 'Force', 'Energy', 'Power', 'Strength', 'Might', 'Vigor',
    'Aurora', 'Eclipse', 'Comet', 'Meteor', 'Asteroid', 'Nebula', 'Galaxy', 'Constellation',
    'Crimson', 'Azure', 'Emerald', 'Amber', 'Violet', 'Indigo', 'Scarlet', 'Cyan',
    'Frost', 'Flame', 'Ice', 'Fire', 'Water', 'Earth', 'Wind', 'Storm',
    'Sonic', 'Supersonic', 'Hypersonic', 'Light', 'Sound', 'Wave', 'Pulse', 'Beat',
    'Rapid', 'Instant', 'Immediate', 'Sudden', 'Fleet', 'Nimble', 'Agile', 'Swift',
    'Majestic', 'Regal', 'Imperial', 'Elegant', 'Graceful', 'Refined', 'Sublime', 'Exquisite'
  ],

  // Animals & Creatures Nouns
  nouns: [
    'Tiger', 'Eagle', 'Shark', 'Lion', 'Wolf', 'Bear', 'Falcon', 'Hawk',
    'Phoenix', 'Dragon', 'Jaguar', 'Panther', 'Leopard', 'Cobra', 'Viper', 'Serpent',
    'Griffin', 'Unicorn', 'Pegasus', 'Kraken', 'Leviathan', 'Hydra', 'Cerberus', 'Chimera',
    'Raven', 'Crow', 'Owl', 'Condor', 'Albatross', 'Vulture', 'Harrier', 'Osprey',
    'Cheetah', 'Lynx', 'Puma', 'Cougar', 'Bobcat', 'Wildcat', 'Saber', 'Panther',
    'Rhino', 'Elephant', 'Hippo', 'Gorilla', 'Orangutan', 'Chimp', 'Baboon', 'Macaque',
    'Dolphin', 'Orca', 'Whale', 'Barracuda', 'Marlin', 'Tuna', 'Swordfish', 'Shark',
    'Stallion', 'Mustang', 'Thoroughbred', 'Centaur', 'Satyr', 'Faun', 'Unicorn', 'Pegasus',
    'Grizzly', 'Polar', 'Panda', 'Koala', 'Kangaroo', 'Wallaby', 'Wombat', 'Tasmanian',
    'Scorpion', 'Spider', 'Tarantula', 'Mantis', 'Beetle', 'Dragonfly', 'Butterfly', 'Moth',
    'Python', 'Anaconda', 'Rattlesnake', 'Mamba', 'Adder', 'Asp', 'Cobra', 'Viper',
    'Wyvern', 'Drake', 'Basilisk', 'Cockatrice', 'Gargoyle', 'Hippogriff', 'Griffin', 'Dragon',
    'Firebird', 'Thunderbird', 'Roc', 'Garuda', 'Simurgh', 'Ziz', 'Bennu', 'Phoenix',
    'Cthulhu', 'Scylla', 'Charybdis', 'Jormungandr', 'Nidhogg', 'Hydra', 'Kraken', 'Leviathan',
    'Coyote', 'Fox', 'Jackal', 'Dingo', 'Hyena', 'Wild', 'Feral', 'Wolf',
    'Kodiak', 'Black', 'Brown', 'Cave', 'Grizzly', 'Polar', 'Panda', 'Bear',
    'Hammerhead', 'Mako', 'Bull', 'Reef', 'Great', 'White', 'Tiger', 'Shark',
    'Bottlenose', 'Spinner', 'Risso', 'Striped', 'Spotted', 'Fraser', 'Common', 'Dolphin',
    'Blue', 'Humpback', 'Killer', 'Sperm', 'Beluga', 'Narwhal', 'Bowhead', 'Whale',
    'Blackfish', 'Grampus', 'Sea', 'Wolf', 'Killer', 'Orca', 'Dolphin', 'Whale'
  ],

  // Single-word powerful names
  longWords: [
    'Thunderbolt', 'Lightning', 'Firestorm', 'Blizzard', 'Hurricane', 'Tornado',
    'Avalanche', 'Volcano', 'Tsunami', 'Earthquake', 'Supernova', 'Blackhole',
    'MilkyWay', 'Andromeda', 'Constellation', 'Meteorite', 'Asteroid', 'Comet',
    'Phantom', 'Shadow', 'Mystic', 'Enigma', 'Riddle', 'Puzzle', 'Cipher',
    'Vortex', 'Quantum', 'Matrix', 'Nexus', 'Prism', 'Crystal', 'Oracle',
    'Sage', 'Wizard', 'Sorcerer', 'Mage', 'Warlock', 'Druid', 'Shaman',
    'Tempest', 'Cyclone', 'Typhoon', 'Monsoon', 'Squall', 'Storm', 'Thunder', 'Lightning',
    'Inferno', 'Blaze', 'Flame', 'Fire', 'Ember', 'Spark', 'Torch', 'Beacon',
    'Aurora', 'Eclipse', 'Nova', 'Supernova', 'Quasar', 'Pulsar', 'Nebula', 'Galaxy',
    'Whirlpool', 'Maelstrom', 'Vortex', 'Tornado', 'Cyclone', 'Hurricane', 'Typhoon', 'Monsoon',
    'Specter', 'Wraith', 'Ghost', 'Spirit', 'Soul', 'Essence', 'Aura', 'Phantom',
    'Mystery', 'Enigma', 'Riddle', 'Puzzle', 'Conundrum', 'Paradox', 'Anomaly', 'Mystic',
    'Prophet', 'Seer', 'Visionary', 'Sage', 'Wise', 'Guru', 'Master', 'Oracle',
    'Necromancer', 'Enchanter', 'Conjurer', 'Illusionist', 'Witch', 'Wizard', 'Sorcerer', 'Mage',
    'Priest', 'Monk', 'Hermit', 'Ascetic', 'Mystic', 'Sage', 'Druid', 'Shaman',
    'Atomic', 'Nuclear', 'Molecular', 'Particle', 'Wave', 'Field', 'Force', 'Quantum',
    'Grid', 'Network', 'Web', 'Mesh', 'Lattice', 'Framework', 'Structure', 'Matrix',
    'Hub', 'Core', 'Center', 'Heart', 'Soul', 'Essence', 'Spirit', 'Nexus',
    'Gem', 'Jewel', 'Diamond', 'Ruby', 'Emerald', 'Sapphire', 'Prism', 'Crystal',
    'Quartz', 'Amethyst', 'Topaz', 'Opal', 'Pearl', 'Amber', 'Jade', 'Crystal'
  ],

  // Tech & Digital themed (curated for cool session names)
  techWords: [
    'Neural', 'Digital', 'Cyber', 'Virtual', 'Hyper', 'Meta', 'Nano', 'Quantum',
    'Binary', 'Code', 'Byte', 'Bit', 'Pixel', 'Vector', 'Matrix', 'Grid',
    'Cloud', 'Server', 'Node', 'Link', 'Chain', 'Block', 'Token', 'Hash',
    'Stream', 'Flow', 'Pulse', 'Beat', 'Rhythm', 'Wave', 'Signal', 'Frequency',
    'Laser', 'Beam', 'Ray', 'Photon', 'Electron', 'Proton', 'Neutron', 'Atom',
    'Circuit', 'Board', 'Chip', 'Core', 'CPU', 'GPU', 'RAM', 'ROM',
    'Network', 'Router', 'Switch', 'Hub', 'Gateway', 'Bridge', 'Tunnel', 'VPN',
    'Protocol', 'API', 'SDK', 'Framework', 'Library', 'Module', 'Package', 'Bundle',
    'Algorithm', 'Function', 'Method', 'Process', 'Thread', 'Task', 'Job', 'Work',
    'Database', 'Cache', 'Index', 'Query', 'Table', 'Row', 'Column', 'Field',
    'Server', 'Client', 'Peer', 'Host', 'Guest', 'User', 'Admin', 'Root',
    'Security', 'Encryption', 'Decryption', 'Hash', 'Salt', 'Key', 'Token', 'Session',
    'Backup', 'Archive', 'Snapshot', 'Clone', 'Mirror', 'Copy', 'Duplicate', 'Replica',
    'Deploy', 'Release', 'Build', 'Compile', 'Execute', 'Run', 'Start', 'Stop',
    'Monitor', 'Log', 'Track', 'Trace', 'Debug', 'Profile', 'Analyze', 'Optimize',
    'Scale', 'Load', 'Balance', 'Distribute', 'Replicate', 'Sync', 'Async', 'Parallel',
    'Queue', 'Stack', 'Heap', 'Tree', 'Graph', 'List', 'Array', 'Set',
    'String', 'Integer', 'Float', 'Boolean', 'Null', 'Undefined', 'Object', 'Class',
    'Interface', 'Abstract', 'Concrete', 'Generic', 'Template', 'Pattern', 'Model', 'View',
    'Controller', 'Service', 'Repository', 'Factory', 'Builder', 'Singleton', 'Observer', 'Strategy',
    'Adapter', 'Decorator', 'Facade', 'Proxy', 'Bridge', 'Composite', 'Flyweight', 'Command',
    'Iterator', 'Mediator', 'Memento', 'State', 'Visitor', 'Chain', 'Responsibility', 'Interpreter',
    'Template', 'Method', 'Hook', 'Callback', 'Promise', 'Future', 'Async', 'Await',
    'Event', 'Listener', 'Handler', 'Emitter', 'Dispatcher', 'Broker', 'Message', 'Queue',
    'Stream', 'Pipeline', 'Filter', 'Map', 'Reduce', 'Fold', 'Scan', 'Zip',
    'Merge', 'Split', 'Join', 'Concat', 'Append', 'Prepend', 'Insert', 'Delete',
    'Update', 'Upsert', 'Patch', 'Replace', 'Transform', 'Convert', 'Parse', 'Serialize',
    'Deserialize', 'Encode', 'Decode', 'Compress', 'Decompress', 'Encrypt', 'Decrypt', 'Hash',
    'Sign', 'Verify', 'Authenticate', 'Authorize', 'Validate', 'Sanitize', 'Escape', 'Unescape',
    'Render', 'Paint', 'Draw', 'Sketch', 'Design', 'Layout', 'Style', 'Theme',
    'Component', 'Element', 'Widget', 'Control', 'Button', 'Input', 'Form', 'Field',
    'Label', 'Text', 'Image', 'Video', 'Audio', 'Canvas', 'SVG', 'WebGL',
    'Animation', 'Transition', 'Transform', 'Rotation', 'Scale', 'Translate', 'Skew', 'Perspective',
    'Gradient', 'Shadow', 'Blur', 'Opacity', 'Filter', 'Mask', 'Clip', 'Overflow',
    'Scroll', 'Zoom', 'Pan', 'Drag', 'Drop', 'Swipe', 'Pinch', 'Rotate',
    'Click', 'Double', 'Right', 'Middle', 'Wheel', 'Touch', 'Gesture', 'Motion',
    'Keyboard', 'Mouse', 'Touchpad', 'Trackpad', 'Stylus', 'Pen', 'Finger', 'Hand',
    'Screen', 'Display', 'Monitor', 'Projector', 'TV', 'Tablet', 'Phone', 'Watch',
    'Camera', 'Microphone', 'Speaker', 'Headphone', 'Earbud', 'Headset', 'VR', 'AR',
    'Mixed', 'Reality', 'Virtual', 'Augmented', 'Extended', 'Metaverse', 'Universe', 'World',
    'Space', 'Dimension', 'Plane', 'Level', 'Layer', 'Depth', 'Height', 'Width',
    'Length', 'Distance', 'Position', 'Location', 'Coordinate', 'Vector', 'Point', 'Line',
    'Curve', 'Bezier', 'Spline', 'Path', 'Route', 'Trail', 'Track', 'Trace',
    'Shape', 'Circle', 'Square', 'Rectangle', 'Triangle', 'Polygon', 'Ellipse', 'Arc',
    'Color', 'Red', 'Green', 'Blue', 'Yellow', 'Cyan', 'Magenta', 'Black',
    'White', 'Gray', 'Grey', 'Silver', 'Gold', 'Bronze', 'Copper', 'Brass',
    'Texture', 'Material', 'Surface', 'Finish', 'Gloss', 'Matte', 'Rough', 'Smooth',
    'Light', 'Dark', 'Bright', 'Dim', 'Shade', 'Tint', 'Tone', 'Hue',
    'Saturation', 'Value', 'Luminance', 'Brightness', 'Contrast', 'Gamma', 'Exposure', 'Gain',
    'Noise', 'Grain', 'Artifact', 'Aliasing', 'Anti', 'Aliasing', 'Filtering', 'Sampling',
    'Resolution', 'Pixel', 'Density', 'DPI', 'PPI', 'Megapixel', 'K', '4K',
    '8K', 'HD', 'Full', 'SD', 'Standard', 'Definition', 'High', 'Ultra',
    'Frame', 'Rate', 'FPS', 'Frames', 'Per', 'Second', 'Refresh', 'Hz',
    'Hertz', 'Kilohertz', 'Megahertz', 'Gigahertz', 'Terahertz', 'Frequency', 'Bandwidth', 'Throughput',
    'Latency', 'Delay', 'Lag', 'Jitter', 'Packet', 'Loss', 'Retransmission', 'Timeout',
    'Connection', 'Socket', 'Port', 'Protocol', 'TCP', 'UDP', 'HTTP', 'HTTPS',
    'WebSocket', 'SSH', 'FTP', 'SFTP', 'SMTP', 'POP', 'IMAP', 'DNS',
    'Domain', 'Name', 'System', 'IP', 'Address', 'IPv4', 'IPv6', 'Subnet',
    'Mask', 'Gateway', 'Router', 'Switch', 'Hub', 'Bridge', 'Repeater', 'Amplifier',
    'Antenna', 'Signal', 'Wave', 'Frequency', 'Amplitude', 'Phase', 'Modulation', 'Demodulation',
    'Encoding', 'Decoding', 'Compression', 'Decompression', 'Encryption', 'Decryption', 'Hashing', 'Salting',
    'Key', 'Exchange', 'Handshake', 'Certificate', 'SSL', 'TLS', 'PKI', 'CA',
    'Certificate', 'Authority', 'Public', 'Private', 'Symmetric', 'Asymmetric', 'RSA', 'AES',
    'DES', '3DES', 'Blowfish', 'Twofish', 'Serpent', 'Camellia', 'ChaCha', 'Poly1305',
    'SHA', 'MD5', 'SHA1', 'SHA256', 'SHA512', 'SHA3', 'Keccak', 'BLAKE',
    'BLAKE2', 'BLAKE3', 'Argon2', 'Scrypt', 'PBKDF2', 'bcrypt', 'HKDF', 'HMAC',
    'MAC', 'Message', 'Authentication', 'Code', 'CRC', 'Checksum', 'Parity', 'ECC',
    'Error', 'Correction', 'Code', 'Reed', 'Solomon', 'Hamming', 'BCH', 'LDPC',
    'Turbo', 'Convolutional', 'Block', 'Stream', 'Cipher', 'Blockchain', 'Cryptocurrency', 'Bitcoin',
    'Ethereum', 'Smart', 'Contract', 'Token', 'NFT', 'Non', 'Fungible', 'DAO',
    'Decentralized', 'Autonomous', 'Organization', 'DeFi', 'Finance', 'Staking', 'Mining', 'Proof',
    'Work', 'Stake', 'Authority', 'Consensus', 'Byzantine', 'Fault', 'Tolerance', 'RAFT',
    'Paxos', 'PBFT', 'Practical', 'BFT', 'Tendermint', 'Cosmos', 'Polkadot', 'Cardano',
    'Solana', 'Avalanche', 'Polygon', 'Arbitrum', 'Optimism', 'Base', 'zkSync', 'StarkNet',
    'Zero', 'Knowledge', 'Proof', 'ZK', 'SNARK', 'STARK', 'PLONK', 'Bulletproofs',
    'Rollup', 'Layer', '2', 'L2', 'Sidechain', 'State', 'Channel', 'Lightning',
    'Network', 'Payment', 'Channel', 'HTLC', 'Hashed', 'Timelock', 'Contract', 'Multisig',
    'Threshold', 'Signature', 'Schnorr', 'BLS', 'Edwards', 'Curve', 'Ed25519', 'Secp256k1',
    'Elliptic', 'Curve', 'Cryptography', 'ECC', 'ECDSA', 'ECDH', 'ECIES', 'ECMQV',
    'Post', 'Quantum', 'Cryptography', 'PQC', 'Lattice', 'Code', 'Hash', 'Based',
    'Multivariate', 'Isogeny', 'Supersingular', 'Elliptic', 'Curve', 'SIKE', 'CRYSTALS',
    'Kyber', 'Dilithium', 'FALCON', 'SPHINCS', 'Picnic', 'Rainbow', 'GeMSS', 'LUOV',
    'MQDSS', 'Gravity', 'Sphincs', 'XMSS', 'XMSSMT', 'LMS', 'HSS', 'SPHINCS',
    'Plus', 'Minus', 'Shake', 'Haraka', 'AES', 'GCM', 'CCM', 'OCB',
    'EAX', 'ChaCha20', 'Poly1305', 'AEAD', 'Authenticated', 'Encryption', 'Associated', 'Data',
    'Nonce', 'IV', 'Initialization', 'Vector', 'Counter', 'CTR', 'CBC', 'CFB',
    'OFB', 'XTS', 'LRW', 'FDE', 'Full', 'Disk', 'Encryption', 'LUKS',
    'DM', 'Crypt', 'TrueCrypt', 'VeraCrypt', 'BitLocker', 'FileVault', 'eCryptfs', 'EncFS',
    'GPG', 'GnuPG', 'PGP', 'Pretty', 'Good', 'Privacy', 'OpenPGP', 'S',
    'MIME', 'Multipurpose', 'Internet', 'Mail', 'Extensions', 'Base64', 'Quoted', 'Printable',
    'QP', 'URL', 'Encoding', 'Percent', 'Hex', 'Hexadecimal', 'Binary', 'Octal',
    'Decimal', 'ASCII', 'UTF', '8', '16', '32', 'Unicode', 'Code',
    'Point', 'Grapheme', 'Cluster', 'Normalization', 'NFC', 'NFD', 'NFKC', 'NFKD',
    'Collation', 'Sorting', 'Comparison', 'Locale', 'Internationalization', 'i18n', 'Localization', 'l10n',
    'Translation', 'Transliteration', 'Transcription', 'Romanization', 'Pinyin', 'Hepburn', 'Revised', 'Wade',
    'Giles', 'Yale', 'McCune', 'Reischauer', 'ISO', 'International', 'Organization', 'Standardization',
    'IEC', 'Electrotechnical', 'Commission', 'ITU', 'Telecommunication', 'Union', 'IEEE', 'Institute',
    'Electrical', 'Electronics', 'Engineers', 'ANSI', 'American', 'National', 'Standards', 'Institute',
    'NIST', 'National', 'Institute', 'Standards', 'Technology', 'FIPS', 'Federal', 'Information',
    'Processing', 'Standard', 'Common', 'Criteria', 'CC', 'EAL', 'Evaluation', 'Assurance',
    'Level', 'FIPS', '140', '2', 'Security', 'Requirements', 'Cryptographic', 'Modules',
    'CMVP', 'Cryptographic', 'Module', 'Validation', 'Program', 'CAVP', 'Cryptographic', 'Algorithm',
    'Validation', 'Program', 'NIST', 'SP', 'Special', 'Publication', '800', 'Series',
    'FIPS', 'PUB', 'Federal', 'Information', 'Processing', 'Standard', 'Publication', 'NIST',
    'IR', 'Internal', 'Report', 'ITL', 'Information', 'Technology', 'Laboratory', 'Bulletin',
    'CSRC', 'Computer', 'Security', 'Resource', 'Center', 'Crypto', 'Standards', 'Workshop',
    'CSW', 'Post', 'Quantum', 'Cryptography', 'PQC', 'Standardization', 'Process', 'Round',
    '1', '2', '3', '4', 'Finalists', 'Alternates', 'Backup', 'Candidates',
    'NIST', 'PQC', 'Standardization', 'Process', 'Round', '1', '2', '3',
    '4', 'Finalists', 'Alternates', 'Backup', 'Candidates', 'Lattice', 'Based', 'Cryptography',
    'LBC', 'Learning', 'With', 'Errors', 'LWE', 'Ring', 'RWE', 'Module',
    'MLWE', 'Polynomial', 'PLWE', 'Torus', 'TLWE', 'RLWE', 'MLWE', 'PLWE',
    'TLWE', 'NTRU', 'Number', 'Theory', 'Research', 'Unit', 'NTRU', 'Encrypt',
    'NTRU', 'Prime', 'NTRU', 'HRSS', 'Hoffstein', 'Pipher', 'Silverman', 'NTRU',
    'HRSS', 'Hoffstein', 'Pipher', 'Silverman', 'NTRU', 'Prime', 'NTRU', 'Encrypt',
    'NTRU', 'HRSS', 'Hoffstein', 'Pipher', 'Silverman', 'NTRU', 'Prime', 'NTRU',
    'Encrypt', 'NTRU', 'HRSS', 'Hoffstein', 'Pipher', 'Silverman', 'NTRU', 'Prime',
    'NTRU', 'Encrypt', 'NTRU', 'HRSS', 'Hoffstein', 'Pipher', 'Silverman', 'NTRU',
    'Prime', 'NTRU', 'Encrypt', 'NTRU', 'HRSS', 'Hoffstein', 'Pipher', 'Silverman',
    'NTRU', 'Prime', 'NTRU', 'Encrypt', 'NTRU', 'HRSS', 'Hoffstein', 'Pipher', 'Silverman'
  ]
};
